baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
title = "ASP.NET Core Essentials"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/IEvangelist/ASP.NET-Core-Essentials-Workshop"
  author = "David Pine"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]