baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
title = "ASP.NET Core Essentials"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/IEvangelist/ASP.NET-Core-Essentials-Workshop"
  description = "ASP.NET Core Essentials - Developer Workshop by David Pine."
  author = "David Pine"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableAssetsBusting = false
  themeVariant = "custom"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github Repository"
identifier = "workshop"
url = "https://github.com/IEvangelist/AspNet.Essentials.Workshop"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-twitter'></i> Follow @davidpine7"
identifier = "twitter"
url = "https://twitter.com/davidpine7"
weight = 2